language: python
python:
  - 3.6
  - 3.5
  - 3.7
install:
  - make install
script:
  - make test
deploy:
  provider: heroku
  api_key: ...
  app:
    master: my-app-staging
    production: my-app-production